### ISSUE TITLE
TSS463 availability

### ISSUE THREAD

**Issue by karolp1993** [morcibacsi/PSAVanCanBridgeHW#2]
Hi. Nice project, great job! I will try to build your project on my 307 2004. I just wondered earlier, where did you find TSS463 to buy? Or it's necessary to desolder from instrument cluster or display?

**Comment by morcibacsi** [comment]
Thanks. I bought it from aliexpress [from this seller](https://www.aliexpress.com/item/32947768756.html). But salvaging it from a display or an instrument cluster is also a good option. And soon I think it will be the only option as these parts are getting out of stock.
