### ISSUE TITLE
Wont turn on. Issue with termination resistors

### ISSUE THREAD

**Issue by najdanovicivan** [morcibacsi/PSAVanCanBridgeHW#4]
When 120 ohm termination resistors are present on ether CAN or VAN line things will not work

VAN issue - The instrument gauge started to flicker all indicators turns on same way like the VAN line is disconnected
CAN issue - The screen does not turn on and RD45 will just spin CD motor for a fraction of second and this will happen in loop

I resolved the issue by removing  R3 and R4 resistors.

Tested with RD45 on 206CC

**Comment by morcibacsi** [comment]
Thanks for reporting. It was known before, I just forgot to update the readme with the information. Added a warning in 14ef456b4231d8f84fe3717f5a421d99a402b76a
